services:
  filebrowser:
    image: gtstef/filebrowser:beta
    container_name: filebrowser
    ports:
      - 80:8900
    restart: unless-stopped
    # user: filebrowser
    volumes:
      - /home/apps/mnt/filebrowser/data:/home/filebrowser/data
      - /mnt/filebrowser:/files
      # - /other/dir:/dir # Add other sources
    environment:
      - "FILEBROWSER_CONFIG=data/config.yml" # using our config file at ./data/config.yml
