services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    volumes:
      - /mnt/youtube:/youtube
      - /home/apps/mnt/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_CON=redis://archivist-redis:6379
      - TA_HOST=https://youtube.doxy.moe  # set your host name with protocol and port
      - TA_USERNAME=admin           # your initial TA credentials
      - TZ=America/Los_Angeles                # set your time zone
      - TA_LOGIN_AUTH_MODE=local
    env_file: ".env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /home/apps/mnt/tubearchivist/redis-data:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.19.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    env_file: ".env"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/apps/mnt/tubearchivist/es-data:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
