; /etc/nut/ups.conf
; [nutdev1]
    ; driver = "usbhid-ups"
    ; port = "auto"
    ; vendorid = "0764"
    ; productid = "0501"
    ; product = "ST Series"
    ; vendor = "CPS"
    ; bus = "001"
    ; device = "009"
    ; busport = "003"

[ups]
    driver = usbhid-ups
    port = auto
    desc = "CyberPower UPS"
