# /opt/stacks/caddy/docker-compose.yml
services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/doxy/mnt/caddy/data:/data
      - /home/doxy/mnt/caddy/config:/config
      - /var/log/caddy:/var/log/caddy
    env_file:
      - path: ./.env
        required: true
    # environment:
    #   PORKBUN_API_KEY: <api-key>
    #   PORKBUN_SECRET_API_KEY: <secret-api-key>
    #   CROWDSEC_BOUNCER_KEY: <bouncer-api-key>
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gatekeeper-net
networks:
  gatekeeper-net:
    external: true
